'use client';
import React, { useState } from 'react';
import { Modal } from '../ui/Modal';
import { AppIcon } from '../ui/app-icon';
import { useAuth } from '@/lib/auth-context';
import { isProUser } from '@/lib/pro-features';
import { useHousehold } from '@/lib/household-context';
import type { MonthBudget } from '@/lib/store';

export function HouseholdModal({ isOpen, onClose, onOpenPro, month }: { isOpen: boolean; onClose: () => void; onOpenPro?: () => void; month?: MonthBudget }) {
  const { profile } = useAuth(); const isPro = isProUser(profile); const { household, members, isOwner, create, addProfile, invite, acceptInvite, updateMember } = useHousehold();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [memberName, setMemberName] = useState(''); const [role, setRole] = useState<'editor' | 'viewer'>('editor'); const [code, setCode] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const run = async (fn: () => Promise<void>) => { setBusy(true); setNotice(''); try { await fn(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setBusy(false); } };
  const contributions = members.filter(m => m.status === 'active' && m.role !== 'profile').map(m => ({ member: m, total: [...(month?.variableExpenses || []), ...(month?.fixedExpenses || [])].filter(e => e.payerMemberId === m.id).reduce((sum, e) => sum + e.amount, 0) }));
  const paidTotal = contributions.reduce((sum, item) => sum + item.total, 0);
  const share = contributions.length ? paidTotal / contributions.length : 0;
  return <Modal isOpen={isOpen} onClose={onClose} title="Household collaboration" className="max-w-lg"><div className="space-y-5">
    {!household ? <>
      <p className="text-body-sm text-on-surface-variant">Create a shared household to track who paid, collaborate live, and see contribution balances.</p>
      {!isPro ? <button onClick={onOpenPro} className="w-full rounded-xl bg-primary py-3 font-bold text-on-primary">Unlock with Pro</button> : <><input value={name} onChange={e => setName(e.target.value)} placeholder="Household name (e.g. The Silva family)" className="w-full rounded-xl border border-outline-variant bg-surface p-3" /><button disabled={busy} onClick={() => run(async () => { await create(name); setNotice('Household created. Your personal budget stays private; new shared activity is stored in this workspace.'); })} className="w-full rounded-xl bg-primary py-3 font-bold text-on-primary disabled:opacity-50">Create household</button></>}
      <div className="border-t border-outline-variant pt-4"><label className="text-sm font-bold">Have an invitation code?</label><div className="mt-2 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Paste invitation code" className="min-w-0 flex-1 rounded-xl border border-outline-variant bg-surface p-3"/><button disabled={!code || busy} onClick={() => run(async () => { await acceptInvite(code); setNotice('You joined the household.'); })} className="rounded-xl bg-primary px-4 font-bold text-on-primary disabled:opacity-50">Join</button></div></div>
    </> : <>
      <div className="rounded-xl bg-primary/10 p-4"><p className="font-bold text-on-surface">{household.name}</p><p className="text-sm text-on-surface-variant">{members.filter(m=>m.status === 'active').length} active members · shared budget is live</p></div>
      <div className="space-y-2">{members.map(member => <div key={member.id} className="flex items-center gap-3 rounded-xl border border-outline-variant p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full font-bold text-white" style={{backgroundColor:member.avatarColor}}>{member.displayName[0]}</span><div className="min-w-0 flex-1"><p className="font-semibold">{member.displayName}</p><p className="truncate text-xs text-on-surface-variant">{member.role} · {member.status}{member.email ? ` · ${member.email}` : ''}</p></div>{isOwner && member.role !== 'owner' && <button onClick={() => run(() => updateMember({...member, status: member.status === 'inactive' ? 'active' : 'inactive'}))} className="text-xs font-bold text-primary">{member.status === 'inactive' ? 'Restore' : 'Remove'}</button>}</div>)}</div>
      {contributions.length > 0 && <div className="border-t border-outline-variant pt-4"><p className="mb-2 font-bold">This month&apos;s contributions</p><div className="space-y-2">{contributions.map(({member,total}) => { const balance = total - share; return <div key={member.id} className="flex justify-between rounded-lg bg-surface-container p-3 text-sm"><span>{member.displayName}</span><span className="font-semibold">{total.toFixed(2)} · <span className={balance >= 0 ? 'text-primary' : 'text-error'}>{balance >= 0 ? '+' : ''}{balance.toFixed(2)}</span></span></div>})}</div><p className="mt-2 text-xs text-on-surface-variant">Balance compares each active collaborator&apos;s paid expenses with an equal share. Use it as a settle-up guide; no money is moved by Flousy.</p></div>}
      {isOwner && <div className="space-y-3 border-t border-outline-variant pt-4"><div><p className="font-bold">Add a profile-only member</p><p className="mt-1 text-xs text-on-surface-variant">For a child or someone without an account. They appear in Paid by and reports, but cannot sign in or view the household.</p></div><div className="flex gap-2"><input value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Name (no login needed)" className="min-w-0 flex-1 rounded-xl border border-outline-variant bg-surface p-3"/><button disabled={!memberName || busy} onClick={() => run(async()=>{await addProfile(memberName);setMemberName('');})} className="rounded-xl bg-primary px-3 font-bold text-on-primary disabled:opacity-50">Add</button></div><div className="grid grid-cols-[1fr_auto_auto] gap-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email to invite" className="min-w-0 rounded-xl border border-outline-variant bg-surface p-3"/><select value={role} onChange={e=>setRole(e.target.value as 'editor'|'viewer')} className="rounded-xl border border-outline-variant bg-surface px-2"><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button disabled={!email || busy} onClick={() => run(async()=>{const id=await invite(memberName || email.split('@')[0], email, role); setNotice(`Invite created. Share this secure code with ${email}: ${id}`);setEmail('');})} className="rounded-xl bg-primary px-3 font-bold text-on-primary disabled:opacity-50">Invite</button></div><p className="text-xs text-on-surface-variant">Invite codes are email-bound and expire after 14 days. Connect an email provider later to send them automatically.</p></div>}
    </>}
    {notice && <p role="status" className="rounded-lg bg-surface-container p-3 text-sm text-on-surface">{notice}</p>}
  </div></Modal>;
}
