'use client';
import React, { useState } from 'react';
import { Modal } from '../ui/Modal';
import { AppIcon } from '../ui/app-icon';
import { useAuth } from '@/lib/auth-context';
import { isProUser } from '@/lib/pro-features';
import { useHousehold } from '@/lib/household-context';
import type { MonthBudget } from '@/lib/store';
import { HOUSEHOLD_AREAS, type HouseholdPermissions } from '@/lib/household-rbac';

export function HouseholdModal({ isOpen, onClose, onOpenPro, month, initialInviteCode }: { isOpen: boolean; onClose: () => void; onOpenPro?: () => void; month?: MonthBudget; initialInviteCode?: string }) {
  const { profile } = useAuth(); const isPro = isProUser(profile); const { household, members, isOwner, create, invite, acceptInvite, updateMember } = useHousehold();
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [memberName, setMemberName] = useState(''); const [role, setRole] = useState<'editor' | 'viewer' | 'custom'>('custom'); const [permissions, setPermissions] = useState<HouseholdPermissions>({ expenses: 'editOwn', invoices: 'editOwn' }); const [code, setCode] = useState(initialInviteCode || ''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false);
  const run = async (fn: () => Promise<void>) => { setBusy(true); setNotice(''); try { await fn(); } catch (e) { setNotice(e instanceof Error ? e.message : 'Something went wrong.'); } finally { setBusy(false); } };
  const contributions = members.filter(m => m.status === 'active' && m.role !== 'profile').map(m => ({ member: m, total: [...(month?.variableExpenses || []), ...(month?.fixedExpenses || [])].filter(e => e.payerMemberId === m.id).reduce((sum, e) => sum + e.amount, 0) }));
  const paidTotal = contributions.reduce((sum, item) => sum + item.total, 0);
  const share = contributions.length ? paidTotal / contributions.length : 0;
  return <Modal isOpen={isOpen} onClose={onClose} title="Household collaboration" className="max-w-lg"><div className="space-y-5">
    {!household ? <>
      <p className="text-body-sm text-on-surface-variant">Create a shared household to track who paid, collaborate live, and see contribution balances.</p>
      {!isPro ? <button onClick={onOpenPro} className="w-full rounded-xl bg-primary py-3 font-bold text-on-primary">Unlock with Pro</button> : <><input value={name} onChange={e => setName(e.target.value)} placeholder="Household name (e.g. The Silva family)" className="w-full rounded-xl border border-outline-variant bg-surface p-3" /><button disabled={busy} onClick={() => run(async () => { await create(name); setNotice('Household created. Your personal budget stays private; new shared activity is stored in this workspace.'); })} className="w-full rounded-xl bg-primary py-3 font-bold text-on-primary disabled:opacity-50">Create household</button></>}
      <div className="border-t border-outline-variant pt-4"><label className="text-sm font-bold">Have an invitation code?</label><div className="mt-2 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Paste invitation code" className="min-w-0 flex-1 rounded-xl border border-outline-variant bg-surface p-3"/><button disabled={!code || busy} onClick={() => run(async () => { await acceptInvite(code); setNotice('You joined the household.'); })} className="rounded-xl bg-primary px-4 font-bold text-on-primary disabled:opacity-50">Join</button></div></div>
    </> : <>
      <div className="rounded-xl bg-primary/10 p-4"><p className="font-bold text-on-surface">{household.name}</p><p className="text-sm text-on-surface-variant">{members.filter(m=>m.status === 'active').length} active members · shared budget is live</p></div>
      <div className="space-y-2">{members.map(member => <div key={member.id} className="flex items-center gap-3 rounded-xl border border-outline-variant p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full font-bold text-white" style={{backgroundColor:member.avatarColor}}>{member.displayName[0]}</span><div className="min-w-0 flex-1"><p className="font-semibold">{member.displayName}</p><p className="truncate text-xs text-on-surface-variant">{member.role} · {member.status}{member.email ? ` · ${member.email}` : ''}</p></div>{isOwner && member.role !== 'owner' && <button onClick={() => run(() => updateMember({...member, status: member.status === 'inactive' ? 'active' : 'inactive'}))} className="text-xs font-bold text-primary">{member.status === 'inactive' ? 'Restore' : 'Remove'}</button>}</div>)}</div>
      {contributions.length > 0 && <div className="border-t border-outline-variant pt-4"><p className="mb-2 font-bold">This month&apos;s contributions</p><div className="space-y-2">{contributions.map(({member,total}) => { const balance = total - share; return <div key={member.id} className="flex justify-between rounded-lg bg-surface-container p-3 text-sm"><span>{member.displayName}</span><span className="font-semibold">{total.toFixed(2)} · <span className={balance >= 0 ? 'text-primary' : 'text-error'}>{balance >= 0 ? '+' : ''}{balance.toFixed(2)}</span></span></div>})}</div><p className="mt-2 text-xs text-on-surface-variant">Balance compares each active collaborator&apos;s paid expenses with an equal share. Use it as a settle-up guide; no money is moved by Flousy.</p></div>}
      {isOwner && <div className="space-y-3 border-t border-outline-variant pt-4"><div><p className="font-bold">Invite a household member</p><p className="mt-1 text-xs text-on-surface-variant">Choose their access instead of assigning a fixed family role.</p></div><input value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Full name" className="w-full rounded-xl border border-outline-variant bg-surface p-3"/><div className="grid grid-cols-[1fr_auto_auto] gap-2"><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email address" className="min-w-0 rounded-xl border border-outline-variant bg-surface p-3"/><select value={role} onChange={e=>setRole(e.target.value as 'editor'|'viewer'|'custom')} className="rounded-xl border border-outline-variant bg-surface px-2"><option value="custom">Custom access</option><option value="editor">Full access</option><option value="viewer">View only</option></select><button disabled={!email || !memberName || busy} onClick={() => run(async()=>{const id=await invite(memberName, email, role, role === 'custom' ? permissions : undefined); const response = await fetch('/api/household-invitations', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ inviteId: id, email, householdName: household?.name || 'a SmartJib household', role }) }); const responseText=await response.text(); let body:{error?:string}={}; try{body=responseText?JSON.parse(responseText):{}}catch{} if(!response.ok) throw new Error(body.error||`Invitation created but email service is unavailable (${response.status}).`); setNotice(`Invitation email sent to ${email}.`);setEmail('');setMemberName('');})} className="rounded-xl bg-primary px-3 font-bold text-on-primary disabled:opacity-50">Send</button></div>{role === 'custom' && <div className="rounded-xl border border-outline-variant bg-surface-container p-3"><p className="mb-2 text-xs font-bold uppercase tracking-wide text-on-surface-variant">Custom access</p><div className="grid gap-2 sm:grid-cols-2">{HOUSEHOLD_AREAS.map(area => <label key={area.id} className="flex items-center justify-between gap-2 text-sm"><span>{area.label}</span><select value={permissions[area.id] || 'none'} onChange={e=>setPermissions(current=>({...current,[area.id]:e.target.value as any}))} className="rounded-lg border border-outline-variant bg-surface px-2 py-1 text-xs"><option value="none">No access</option><option value="view">View</option>{area.editable && <><option value="editOwn">Edit own</option><option value="editAll">Edit all</option></>}</select></label>)}</div></div>}</div>}
    </>}
    {notice && <p role="status" className="rounded-lg bg-surface-container p-3 text-sm text-on-surface">{notice}</p>}
  </div></Modal>;
}
