import {
  Accessibility,
  Baby,
  BedDouble,
  BookOpen,
  BookmarkPlus,
  BusFront,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeDollarSign,
  Ban,
  Banknote,
  BarChart3,
  Bell,
  BellOff,
  Bike,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarClock,
  Camera,
  Car,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleDashed,
  CircleDollarSign,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  CircleParking,
  CircleX,
  Clapperboard,
  ClipboardCheck,
  Globe,
  Archive as ArchiveIcon,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Coffee,
  CreditCard,
  Activity,
  ArrowRightLeft,
  ChartCandlestick,
  ChartSpline,
  ChevronsRight,
  Crown,
  Droplets,
  Download,
  Dumbbell,
  ExternalLink,
  FileSearch,
  FileText,
  Flashlight,
  FlaskConical,
  FlashlightOff,
  Fuel,
  Gamepad2,
  Gift,
  Grid2X2,
  Grid3x3,
  GraduationCap,
  GripVertical,
  Dices,
  List,
  ListOrdered,
  LogIn,
  HandCoins,
  Heart,
  HeartPulse,
  History,
  Home,
  ImagePlus,
  Info,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Lock,
  LockKeyholeOpen,
  Mail,
  Menu,
  Monitor,
  MonitorSmartphone,
  Moon,
  Music,
  PackagePlus,
  Package2,
  Palette,
  PawPrint,
  Pencil,
  PiggyBank,
  PieChart,
  Pill,
  Plane,
  Phone,
  Receipt,
  ReceiptText,
  RefreshCw,
  RefreshCwOff,
  Repeat2,
  Save,
  Scale,
  Search,
  SearchX,
  Scissors,
  Send,
  Settings,
  Shirt,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TrainFront,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Undo,
  Package,
  User,
  UserPlus,
  Users,
  UsersRound,
  Utensils,
  Wallet,
  WalletCards,
  Wrench,
  Wifi,
  House,
  X,
  EarthIcon,
  Copy,
  Minus,
  PlayCircle,
  QrCode,
  ScanBarcode,
  Share2,
  Table,
  Video,
  VideoOff,
  Flag,
  Hourglass,
  LogOut,
  History as HistoryIcon,
  ZoomIn,
  ZoomOut,
  ArrowLeftRight,
  ArrowUpRight,
  ArrowDownLeft,
  DollarSign,
  Ellipsis,
  EllipsisVertical,
  Percent,
  BellRing,
  Fingerprint,
  Gauge,
  ScanText,
  Table2,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Maps the app's persisted icon identifiers to Lucide icons. Keeping the
 * identifiers means existing category choices continue to work after moving
 * away from Material Symbols.
 */
const icons: Record<string, LucideIcon> = {
  auto_awesome: Sparkles,
  currency_exchange: ArrowLeftRight,
  dataset: Table2,
  document_scanner: ScanText,
  fingerprint: Fingerprint,
  history: History,
  notifications_active: BellRing,
  picture_as_pdf: FileText,
  speed: Gauge,
  storefront: Store,
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  add: CirclePlus,
  add_a_photo: Camera,
  add_box: PackagePlus,
  add_circle: CirclePlus,
  add_task: ClipboardCheck,
  analytics: ChartNoAxesCombined,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  archive: ArchiveIcon,
  attach_money: BadgeDollarSign,
  dollar: DollarSign,
  arrow_outward: ArrowUpRight,
  arrow_inward: ArrowDownLeft,
  call_received: ArrowDownLeft,
  call_made: ArrowUpRight,
  more_horiz: Ellipsis,
  send: Send,
  upload: Upload,
  balance: Scale,
  bar_chart: BarChart3,
  bolt: Lightbulb,
  build: Wrench,
  card_giftcard: Gift,
  calendar_clock: CalendarClock,
  calendar_month: CalendarClock,
  calendar_today: CalendarClock,
  block: Ban,
  event_upcoming: CalendarCheck,
  category: LayoutGrid,
  monitoring: Activity,
  celebration: Sparkles,
  science: FlaskConical,
  sparkles: Sparkles,
  check: Check,
  flag: Flag,
  hourglass_top: Hourglass,
  check_circle: CheckCircle2,
  task_alt: ClipboardCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  cloud_sync: Cloud,
  cloud_done: Cloud,
  cloud_off: CloudOff,
  cloud_upload: CloudUpload,
  cloud_download: CloudDownload,
  content_cut: Scissors,
  close: X,
  credit_card: CreditCard,
  database: FileText,
  dark_mode: Moon,
  delete: Trash2,
  delete_forever: Trash2,
  description: FileText,
  desktop_windows: Monitor,
  devices: MonitorSmartphone,
  directions_bike: Bike,
  directions_bus: BusFront,
  directions_car: Car,
  directions_train: TrainFront,
  download: Download,
  water_drop: Droplets,
  edit: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  event_repeat: CalendarClock,
  expand_more: ChevronDown,
  family_restroom: Users,
  favorite: Heart,
  find_in_page: FileSearch,
  flashlight: Flashlight,
  flashlight_off: FlashlightOff,
  fitness_center: Dumbbell,
  flight: Plane,
  fuel: Fuel,
  grid_view: Grid2X2,
  grid_3x3: Grid3x3,
  group: Accessibility,
  groups: Users,
  user_group: UsersRound,
  group_add: UserPlus,
  drag_indicator: GripVertical,
  dices: Dices,
  list_ordered: ListOrdered,
  list_numbered: ListOrdered,
  log_in: LogIn,
  login: LogIn,
  ticket: Ticket,
  health_and_safety: HeartPulse,
  home: Home,
  hotel: BedDouble,
  info: Info,
  install_mobile: Smartphone,
  ios_share: ExternalLink,
  label: Tag,
  language: EarthIcon,
  light_mode: Lightbulb,
  local_cafe: Coffee,
  local_dining: Utensils,
  local_atm: CircleDollarSign,
  local_activity: Ticket,
  local_parking: CircleParking,
  lock: Lock,
  pending: CircleDashed,
  lock_open: LockKeyholeOpen,
  loop: Repeat2,
  logout: LogOut,
  mail: Mail,
  manage_accounts: User,
  mark_email_unread: Mail,
  medical: HeartPulse,
  medical_services: Stethoscope,
  medication: Pill,
  menu_book: BookOpen,
  more_vert: Menu,
  movie: Clapperboard,
  music_note: Music,
  house: House,
  notifications: Bell,
  payments: Banknote,
  palette: Palette,
  person: User,
  person_add: UserPlus,
  phone: Phone,
  phone_iphone: Smartphone,
  pets: PawPrint,
  pie_chart: PieChart,
  candlestick_chart: ChartCandlestick,
  show_chart: ChartSpline,
  percent: Percent,
  wallet: Wallet,
  swap: ArrowRightLeft,
  chevrons_right: ChevronsRight,
  more_vertical: EllipsisVertical,
  radio_button_unchecked: Circle,
  receipt: Receipt,
  receipt_long: Receipt,
  receipt_text: ReceiptText,
  add_expense: ReceiptText,
  move_money: ArrowRightLeft,
  copy: Copy,
  remove: Minus,
  inventory_2: Package,
  play_circle: PlayCircle,
  qr_code: QrCode,
  scan_barcode: ScanBarcode,
  share: Share2,
  table_rows: Table,
  video_cam: Video,
  visibility_off: VideoOff,
  remove_circle: CircleMinus,
  restaurant: Utensils,
  save: Save,
  savings: PiggyBank,
  scale: Scale,
  school: GraduationCap,
  schedule: CalendarClock,
  settings_backup_restore: HistoryIcon,
  search: Search,
  search_off: SearchX,
  settings: Settings,
  settings_suggest: Settings,
  shield: Shield,
  shirt: Shirt,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  sliders: SlidersHorizontal,
  'sliders-horizontal': SlidersHorizontal,
  sort: ArrowDownUp,
  south: ArrowDown,
  sports_esports: Gamepad2,
  sports_tennis: Circle,
  store: Store,
  subscriptions: Repeat2,
  swap_horiz: ArrowDownUp,
  sync: Repeat2,
  sync_problem: RefreshCwOff,
  travel_explore: Plane,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo,
  upload_file: Upload,
  verified: CheckCircle2,
  warning: CircleAlert,
  wifi: Wifi,
  work: BriefcaseBusiness,
  workspace_premium: Crown,
  wrench: Wrench,
  x: X,
  package: Package,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  // Regressed after the Material→Lucide rebrand: these names are still used
  // in src and were silently falling back to the generic glyph.
  public: Globe,
  refresh: RefreshCw,
  help: CircleHelp,
  list: List,
  view_list: List,
  notifications_off: BellOff,
  trending_down: TrendingDown,
  bookmark_add: BookmarkPlus,
  package_2: Package2,
};


export const APP_ICON_NAMES: ReadonlySet<string> = new Set(Object.keys(icons));

export function AppIcon({ name, title, ...props }: LucideProps & { name: string; title?: string }) {
  const Icon = icons[name] ?? icons.category;
  // Fail loudly in dev: an unknown identifier silently renders the generic
  // grid glyph in production, which is how missing icons go unnoticed.
  if (process.env.NODE_ENV !== 'production' && !icons[name]) {
    console.warn(`[AppIcon] Unknown icon "${name}" — add a mapping in app-icon.tsx.`);
  }
  return (
    <Icon aria-hidden={props['aria-label'] ? undefined : true} {...props}>
      {title && <title>{title}</title>}
    </Icon>
  );
}
