import {
  Accessibility,
  Baby,
  BedDouble,
  BookOpen,
  BusFront,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BriefcaseBusiness,
  CalendarClock,
  Camera,
  Car,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleDollarSign,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  CircleParking,
  CircleX,
  Clapperboard,
  ClipboardCheck,
  Cloud,
  Coffee,
  CreditCard,
  Crown,
  Download,
  Dumbbell,
  ExternalLink,
  FileSearch,
  FileText,
  Flashlight,
  FlashlightOff,
  Fuel,
  Gamepad2,
  Gift,
  Grid2X2,
  Grid3x3,
  GraduationCap,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  ImagePlus,
  Info,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Lock,
  LockKeyholeOpen,
  Mail,
  Menu,
  Monitor,
  Moon,
  Music,
  PackagePlus,
  Palette,
  PawPrint,
  Pencil,
  PiggyBank,
  PieChart,
  Pill,
  Plane,
  Phone,
  Receipt,
  Repeat2,
  Scale,
  Search,
  SearchX,
  Scissors,
  Send,
  Settings,
  Shirt,
  Shield,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Stethoscope,
  Store,
  Tag,
  Ticket,
  TrainFront,
  Trash2,
  TrendingUp,
  Upload,
  Package,
  User,
  Users,
  Utensils,
  Wallet,
  WalletCards,
  Wrench,
  Wifi,
  House,
  X,
  EarthIcon,
  Copy,
  Minus,
  PlayCircle,
  QrCode,
  ScanBarcode,
  Share2,
  Table,
  Video,
  VideoOff,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Maps the app's persisted icon identifiers to Lucide icons. Keeping the
 * identifiers means existing category choices continue to work after moving
 * away from Material Symbols.
 */
const icons: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  add: CirclePlus,
  add_a_photo: Camera,
  add_box: PackagePlus,
  add_circle: CirclePlus,
  add_task: ClipboardCheck,
  analytics: ChartNoAxesCombined,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_money: BadgeDollarSign,
  balance: Scale,
  bar_chart: BarChart3,
  bolt: Lightbulb,
  build: Wrench,
  card_giftcard: Gift,
  calendar_clock: CalendarClock,
  calendar_month: CalendarClock,
  calendar_today: CalendarClock,
  category: LayoutGrid,
  celebration: Sparkles,
  check: Check,
  check_circle: CheckCircle2,
  task_alt: ClipboardCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  cloud_sync: Cloud,
  content_cut: Scissors,
  close: X,
  credit_card: CreditCard,
  database: FileText,
  dark_mode: Moon,
  delete: Trash2,
  delete_forever: Trash2,
  description: FileText,
  desktop_windows: Monitor,
  directions_bike: Bike,
  directions_bus: BusFront,
  directions_car: Car,
  directions_train: TrainFront,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  event_repeat: CalendarClock,
  expand_more: ChevronDown,
  family_restroom: Users,
  favorite: Heart,
  find_in_page: FileSearch,
  flashlight: Flashlight,
  flashlight_off: FlashlightOff,
  fitness_center: Dumbbell,
  flight: Plane,
  fuel: Fuel,
  grid_view: Grid2X2,
  grid_3x3: Grid3x3,
  group: Accessibility,
  health_and_safety: HeartPulse,
  home: Home,
  hotel: BedDouble,
  info: Info,
  install_mobile: Smartphone,
  ios_share: ExternalLink,
  label: Tag,
  language: EarthIcon,
  light_mode: Lightbulb,
  local_cafe: Coffee,
  local_dining: Utensils,
  local_atm: CircleDollarSign,
  local_activity: Ticket,
  local_parking: CircleParking,
  lock: Lock,
  lock_open: LockKeyholeOpen,
  loop: Repeat2,
  mail: Mail,
  manage_accounts: User,
  mark_email_unread: Mail,
  medical: HeartPulse,
  medical_services: Stethoscope,
  medication: Pill,
  menu_book: BookOpen,
  more_vert: Menu,
  movie: Clapperboard,
  music_note: Music,
  house: House,
  notifications: Bell,
  payments: Banknote,
  palette: Palette,
  person: User,
  phone: Phone,
  phone_iphone: Smartphone,
  pets: PawPrint,
  pie_chart: PieChart,
  radio_button_unchecked: Circle,
  receipt: Receipt,
  receipt_long: Receipt,
  copy: Copy,
  remove: Minus,
  inventory_2: Package,
  play_circle: PlayCircle,
  qr_code: QrCode,
  scan_barcode: ScanBarcode,
  share: Share2,
  table_rows: Table,
  video_cam: Video,
  visibility_off: VideoOff,
  remove_circle: CircleMinus,
  restaurant: Utensils,
  savings: PiggyBank,
  scale: Scale,
  school: GraduationCap,
  search: Search,
  search_off: SearchX,
  settings: Settings,
  settings_suggest: Settings,
  shield: Shield,
  shirt: Shirt,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  sliders: SlidersHorizontal,
  sort: ArrowDownUp,
  south: ArrowDown,
  sports_esports: Gamepad2,
  sports_tennis: Circle,
  store: Store,
  subscriptions: Repeat2,
  swap_horiz: ArrowDownUp,
  sync: Repeat2,
  travel_explore: Plane,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  upload_file: Upload,
  verified: CheckCircle2,
  warning: CircleAlert,
  wifi: Wifi,
  work: BriefcaseBusiness,
  workspace_premium: Crown,
  wrench: Wrench,
  x: X,
  package: Package,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
};


export function AppIcon({ name, title, ...props }: LucideProps & { name: string; title?: string }) {
  const Icon = icons[name] ?? icons.category;
  return (
    <Icon aria-hidden={props['aria-label'] ? undefined : true} {...props}>
      {title && <title>{title}</title>}
    </Icon>
  );
}
