import {
  Accessibility,
  Baby,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeDollarSign,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  BriefcaseBusiness,
  CalendarClock,
  Camera,
  Car,
  ChartNoAxesCombined,
  Check,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleAlert,
  CircleDollarSign,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  CircleX,
  Clapperboard,
  ClipboardCheck,
  Cloud,
  Coffee,
  CreditCard,
  Crown,
  Download,
  Dumbbell,
  ExternalLink,
  FileSearch,
  FileText,
  Fuel,
  Gamepad2,
  Gift,
  Grid2X2,
  Grid3x3,
  HandCoins,
  Heart,
  HeartPulse,
  Home,
  ImagePlus,
  Info,
  Landmark,
  LayoutGrid,
  Lightbulb,
  Lock,
  LockKeyholeOpen,
  Mail,
  Menu,
  Monitor,
  Moon,
  Music,
  PackagePlus,
  Palette,
  PawPrint,
  Pencil,
  PiggyBank,
  PieChart,
  Plane,
  Receipt,
  Repeat2,
  Scale,
  Search,
  SearchX,
  Send,
  Settings,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Tag,
  TrendingUp,
  Upload,
  User,
  Users,
  Utensils,
  Wallet,
  Wrench,
  Wifi,
  X,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';

/**
 * Maps the app's persisted icon identifiers to Lucide icons. Keeping the
 * identifiers means existing category choices continue to work after moving
 * away from Material Symbols.
 */
const icons: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  add: CirclePlus,
  add_a_photo: Camera,
  add_box: PackagePlus,
  add_circle: CirclePlus,
  add_task: ClipboardCheck,
  analytics: ChartNoAxesCombined,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  attach_money: BadgeDollarSign,
  balance: Scale,
  bar_chart: BarChart3,
  bolt: Lightbulb,
  build: Wrench,
  card_giftcard: Gift,
  category: LayoutGrid,
  celebration: Sparkles,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  child_care: Baby,
  cloud_sync: Cloud,
  close: X,
  dark_mode: Moon,
  description: FileText,
  desktop_windows: Monitor,
  directions_car: Car,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  event_repeat: CalendarClock,
  family_restroom: Users,
  favorite: Heart,
  find_in_page: FileSearch,
  fitness_center: Dumbbell,
  flight: Plane,
  fuel: Fuel,
  grid_view: Grid2X2,
  grid_3x3: Grid3x3,
  group: Accessibility,
  health_and_safety: HeartPulse,
  home: Home,
  info: Info,
  install_mobile: Smartphone,
  ios_share: ExternalLink,
  label: Tag,
  light_mode: Lightbulb,
  local_cafe: Coffee,
  local_dining: Utensils,
  lock: Lock,
  lock_open: LockKeyholeOpen,
  mail: Mail,
  mark_email_unread: Mail,
  medical: HeartPulse,
  medical_services: HeartPulse,
  more_vert: Menu,
  movie: Clapperboard,
  music_note: Music,
  notifications: Bell,
  payments: Banknote,
  palette: Palette,
  person: User,
  pets: PawPrint,
  pie_chart: PieChart,
  radio_button_unchecked: Circle,
  receipt: Receipt,
  receipt_long: Receipt,
  remove_circle: CircleMinus,
  restaurant: Utensils,
  savings: PiggyBank,
  scale: Scale,
  school: FileText,
  search: Search,
  search_off: SearchX,
  settings: Settings,
  shield: Shield,
  shopping_bag: ShoppingBag,
  sliders: SlidersHorizontal,
  south: ArrowDown,
  sports_esports: Gamepad2,
  sports_tennis: Circle,
  subscriptions: Repeat2,
  swap_horiz: ArrowDownUp,
  sync: Repeat2,
  trending_up: TrendingUp,
  upload_file: Upload,
  verified: CheckCircle2,
  warning: CircleAlert,
  wifi: Wifi,
  work: BriefcaseBusiness,
  workspace_premium: Crown,
};

export function AppIcon({ name, title, ...props }: LucideProps & { name: string; title?: string }) {
  const Icon = icons[name] ?? icons.category;
  return (
    <Icon aria-hidden={props['aria-label'] ? undefined : true} {...props}>
      {title && <title>{title}</title>}
    </Icon>
  );
}
